//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TatooRentACar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARAC
    {
        public int ID { get; set; }
        public string marka { get; set; }
        public string model { get; set; }
        public string plaka { get; set; }
        public string yil { get; set; }
        public string ytip { get; set; }
        public string vtip { get; set; }
        public string maxyas { get; set; }
        public string durum { get; set; }
        public string imaj { get; set; }
        public Nullable<int> akat_id { get; set; }
        public Nullable<int> bkat_id { get; set; }
        public Nullable<double> fiyat { get; set; }
        public Nullable<double> gun { get; set; }
        public Nullable<double> sonuc { get; set; }
    }
}
