//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TatooRentACar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int ID { get; set; }
        public string adsoyad { get; set; }
        public string dyil { get; set; }
        public string etipi { get; set; }
        public string email { get; set; }
        public string sifre { get; set; }
        public string telno { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string adres { get; set; }
        public string durum { get; set; }
    }
}
