//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TatooRentACar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentACarEntities : DbContext
    {
        public RentACarEntities()
            : base("name=RentACarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AKategori> AKategori { get; set; }
        public virtual DbSet<Bkategori> Bkategori { get; set; }
        public virtual DbSet<Ckategori> Ckategori { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<yetkin> yetkin { get; set; }
        public virtual DbSet<Uye> Uye { get; set; }
        public virtual DbSet<ARAC> ARAC { get; set; }
    }
}
